#!/bin/sh
#
# Fuseki SPARQL server
#
# chkconfig:   - 80 20
# description: Run Fuseki SPARQL server.

### BEGIN INIT INFO
# Provides: 
# Required-Start: 
# Required-Stop: 
# Should-Start: 
# Should-Stop: 
# Default-Start: 
# Default-Stop: 
# Short-Description: 
# Description:      
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

prog="fuseki"
EXEC="/usr/local/jena/fuseki/fuseki-server"
ARGS="--config=/usr/local/jena/fuseki/config.ttl"
export FUSEKI_HOME="/usr/local/jena/fuseki"
export JVM_ARGS="-Xmx1024M"

[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

lockfile=/var/lock/subsys/$prog

start() {
    [ -x $EXEC ] || exit 5
    echo -n $"Starting $prog: "
    # if not running, start it up here, usually something like "daemon $EXEC"
    daemon --check=$prog "$EXEC $ARGS &"
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    # stop it here, often "killproc $prog"
    #killproc java
    ps ax | grep fuseki-server | grep -v grep | awk '{print $1}' | xargs kill
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    # run checks to determine if the service is running or use generic status
    status $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        #rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac
exit $?
